runtime: custom
env: flex
service: tv

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.75
  target_concurrent_requests: 100

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

env_variables:
  APP_LOG: errorlog
  APP_KEY: base64:LTy6h/skYzteuqYu1GRDFyVGWG6R4TrGi/CJTviSSdo=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: file
  SESSION_DRIVER: file
