runtime: php74
env: standard

runtime_config:
  document_root: public

manual_scaling:
  instances: 1

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:xlldCTdzZKLYNRHHvwp8z8sOxOfy0BE4U+k+9TJ2qNw=
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: 35.222.113.167
  DB_DATABASE: table_visit
  DB_USERNAME: root
  DB_PASSWORD: npl39HM0MgJvBfbv
  APP_URL: https://halogen-inkwell-326701.uw.r.appspot.com
  # DB_SOCKET: "/"
