runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.75
  target_concurrent_requests: 100

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 25

env_variables:
  APP_KEY: base64:LTy6h/skYzteuqYu1GRDFyVGWG6R4TrGi/CJTviSSdo=
