runtime: php74

handlers:
  - url: /assets
    static_dir: public/assets

env_variables:
  # Put production environment variables here.
  APP_KEY: base64:xlldCTdzZKLYNRHHvwp8z8sOxOfy0BE4U+k+9TJ2qNw=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: 35.222.113.167
  DB_DATABASE: table_visit
  DB_USERNAME: root
  DB_PASSWORD: npl39HM0MgJvBfbv
  APP_URL: https://halogen-inkwell-326701.uw.r.appspot.com
  DB_SOCKET: "/cloudsql/halogen-inkwell-326701:us-central1:table-visit-database"
  APP_ENV: production
